/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.vertrag.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.vertrag.Handy;
import org.xtext.example.mydsl.vertrag.VertragPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Handy</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.vertrag.impl.HandyImpl#isSystem <em>System</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.vertrag.impl.HandyImpl#isMarke <em>Marke</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.vertrag.impl.HandyImpl#isSpeicher <em>Speicher</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HandyImpl extends ElementImpl implements Handy
{
  /**
   * The default value of the '{@link #isSystem() <em>System</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSystem()
   * @generated
   * @ordered
   */
  protected static final boolean SYSTEM_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isSystem() <em>System</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSystem()
   * @generated
   * @ordered
   */
  protected boolean system = SYSTEM_EDEFAULT;

  /**
   * The default value of the '{@link #isMarke() <em>Marke</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMarke()
   * @generated
   * @ordered
   */
  protected static final boolean MARKE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isMarke() <em>Marke</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMarke()
   * @generated
   * @ordered
   */
  protected boolean marke = MARKE_EDEFAULT;

  /**
   * The default value of the '{@link #isSpeicher() <em>Speicher</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSpeicher()
   * @generated
   * @ordered
   */
  protected static final boolean SPEICHER_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isSpeicher() <em>Speicher</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSpeicher()
   * @generated
   * @ordered
   */
  protected boolean speicher = SPEICHER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HandyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VertragPackage.Literals.HANDY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isSystem()
  {
    return system;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSystem(boolean newSystem)
  {
    boolean oldSystem = system;
    system = newSystem;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VertragPackage.HANDY__SYSTEM, oldSystem, system));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isMarke()
  {
    return marke;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMarke(boolean newMarke)
  {
    boolean oldMarke = marke;
    marke = newMarke;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VertragPackage.HANDY__MARKE, oldMarke, marke));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isSpeicher()
  {
    return speicher;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSpeicher(boolean newSpeicher)
  {
    boolean oldSpeicher = speicher;
    speicher = newSpeicher;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VertragPackage.HANDY__SPEICHER, oldSpeicher, speicher));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VertragPackage.HANDY__SYSTEM:
        return isSystem();
      case VertragPackage.HANDY__MARKE:
        return isMarke();
      case VertragPackage.HANDY__SPEICHER:
        return isSpeicher();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VertragPackage.HANDY__SYSTEM:
        setSystem((Boolean)newValue);
        return;
      case VertragPackage.HANDY__MARKE:
        setMarke((Boolean)newValue);
        return;
      case VertragPackage.HANDY__SPEICHER:
        setSpeicher((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VertragPackage.HANDY__SYSTEM:
        setSystem(SYSTEM_EDEFAULT);
        return;
      case VertragPackage.HANDY__MARKE:
        setMarke(MARKE_EDEFAULT);
        return;
      case VertragPackage.HANDY__SPEICHER:
        setSpeicher(SPEICHER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VertragPackage.HANDY__SYSTEM:
        return system != SYSTEM_EDEFAULT;
      case VertragPackage.HANDY__MARKE:
        return marke != MARKE_EDEFAULT;
      case VertragPackage.HANDY__SPEICHER:
        return speicher != SPEICHER_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (system: ");
    result.append(system);
    result.append(", marke: ");
    result.append(marke);
    result.append(", speicher: ");
    result.append(speicher);
    result.append(')');
    return result.toString();
  }

} //HandyImpl
