/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.vertrag.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.mydsl.vertrag.Betriebssystem;
import org.xtext.example.mydsl.vertrag.Element;
import org.xtext.example.mydsl.vertrag.Handy;
import org.xtext.example.mydsl.vertrag.Marke;
import org.xtext.example.mydsl.vertrag.Model;
import org.xtext.example.mydsl.vertrag.Netzanbieter;
import org.xtext.example.mydsl.vertrag.Vertrag;
import org.xtext.example.mydsl.vertrag.VertragFactory;
import org.xtext.example.mydsl.vertrag.VertragPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class VertragPackageImpl extends EPackageImpl implements VertragPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass vertragEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass handyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum netzanbieterEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum betriebssystemEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum markeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.mydsl.vertrag.VertragPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private VertragPackageImpl()
  {
    super(eNS_URI, VertragFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link VertragPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static VertragPackage init()
  {
    if (isInited) return (VertragPackage)EPackage.Registry.INSTANCE.getEPackage(VertragPackage.eNS_URI);

    // Obtain or create and register package
    VertragPackageImpl theVertragPackage = (VertragPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof VertragPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new VertragPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theVertragPackage.createPackageContents();

    // Initialize created meta-data
    theVertragPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theVertragPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(VertragPackage.eNS_URI, theVertragPackage);
    return theVertragPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Elements()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getElement()
  {
    return elementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getElement_Name()
  {
    return (EAttribute)elementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getVertrag()
  {
    return vertragEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getVertrag_Mindestvertragslaufzeit()
  {
    return (EAttribute)vertragEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getVertrag_Datenvolumen()
  {
    return (EAttribute)vertragEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getVertrag_Monatl_kosten()
  {
    return (EAttribute)vertragEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getVertrag_Internetseite()
  {
    return (EAttribute)vertragEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getVertrag_Value()
  {
    return (EAttribute)vertragEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getVertrag_Telefonflat()
  {
    return (EAttribute)vertragEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getVertrag_Smsflat()
  {
    return (EAttribute)vertragEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getVertrag_Geraet()
  {
    return (EReference)vertragEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getHandy()
  {
    return handyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getHandy_System()
  {
    return (EAttribute)handyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getHandy_Marke()
  {
    return (EAttribute)handyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getHandy_Speicher()
  {
    return (EAttribute)handyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getNetzanbieter()
  {
    return netzanbieterEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getBetriebssystem()
  {
    return betriebssystemEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getMarke()
  {
    return markeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VertragFactory getVertragFactory()
  {
    return (VertragFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__ELEMENTS);

    elementEClass = createEClass(ELEMENT);
    createEAttribute(elementEClass, ELEMENT__NAME);

    vertragEClass = createEClass(VERTRAG);
    createEAttribute(vertragEClass, VERTRAG__MINDESTVERTRAGSLAUFZEIT);
    createEAttribute(vertragEClass, VERTRAG__DATENVOLUMEN);
    createEAttribute(vertragEClass, VERTRAG__MONATL_KOSTEN);
    createEAttribute(vertragEClass, VERTRAG__INTERNETSEITE);
    createEAttribute(vertragEClass, VERTRAG__VALUE);
    createEAttribute(vertragEClass, VERTRAG__TELEFONFLAT);
    createEAttribute(vertragEClass, VERTRAG__SMSFLAT);
    createEReference(vertragEClass, VERTRAG__GERAET);

    handyEClass = createEClass(HANDY);
    createEAttribute(handyEClass, HANDY__SYSTEM);
    createEAttribute(handyEClass, HANDY__MARKE);
    createEAttribute(handyEClass, HANDY__SPEICHER);

    // Create enums
    netzanbieterEEnum = createEEnum(NETZANBIETER);
    betriebssystemEEnum = createEEnum(BETRIEBSSYSTEM);
    markeEEnum = createEEnum(MARKE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    vertragEClass.getESuperTypes().add(this.getElement());
    handyEClass.getESuperTypes().add(this.getElement());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Elements(), this.getElement(), null, "elements", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(elementEClass, Element.class, "Element", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getElement_Name(), ecorePackage.getEString(), "name", null, 0, 1, Element.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(vertragEClass, Vertrag.class, "Vertrag", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVertrag_Mindestvertragslaufzeit(), ecorePackage.getEInt(), "mindestvertragslaufzeit", null, 0, 1, Vertrag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVertrag_Datenvolumen(), ecorePackage.getEInt(), "datenvolumen", null, 0, 1, Vertrag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVertrag_Monatl_kosten(), ecorePackage.getEString(), "monatl_kosten", null, 0, 1, Vertrag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVertrag_Internetseite(), ecorePackage.getEString(), "internetseite", null, 0, 1, Vertrag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVertrag_Value(), this.getNetzanbieter(), "value", null, 0, 1, Vertrag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVertrag_Telefonflat(), ecorePackage.getEString(), "telefonflat", null, 0, 1, Vertrag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVertrag_Smsflat(), ecorePackage.getEString(), "smsflat", null, 0, 1, Vertrag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVertrag_Geraet(), this.getHandy(), null, "geraet", null, 0, 1, Vertrag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(handyEClass, Handy.class, "Handy", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getHandy_System(), ecorePackage.getEBoolean(), "system", null, 0, 1, Handy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getHandy_Marke(), ecorePackage.getEBoolean(), "marke", null, 0, 1, Handy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getHandy_Speicher(), ecorePackage.getEBoolean(), "speicher", null, 0, 1, Handy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(netzanbieterEEnum, Netzanbieter.class, "Netzanbieter");
    addEEnumLiteral(netzanbieterEEnum, Netzanbieter.O2);
    addEEnumLiteral(netzanbieterEEnum, Netzanbieter.TELEKOM);
    addEEnumLiteral(netzanbieterEEnum, Netzanbieter.VODAFON);

    initEEnum(betriebssystemEEnum, Betriebssystem.class, "Betriebssystem");
    addEEnumLiteral(betriebssystemEEnum, Betriebssystem.ANDROID);
    addEEnumLiteral(betriebssystemEEnum, Betriebssystem.IOS);

    initEEnum(markeEEnum, Marke.class, "Marke");
    addEEnumLiteral(markeEEnum, Marke.SAMSUNG);
    addEEnumLiteral(markeEEnum, Marke.IPHONE);

    // Create resource
    createResource(eNS_URI);
  }

} //VertragPackageImpl
