/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl.services.VertragGrammarAccess;

@SuppressWarnings("all")
public class VertragSyntacticSequencer extends AbstractSyntacticSequencer {

	protected VertragGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Handy_RightCurlyBracketKeyword_3_a;
	protected AbstractElementAlias match_Handy_RightCurlyBracketKeyword_3_p;
	protected AbstractElementAlias match_Handy_Vertrag___RightCurlyBracketKeyword_3_p_or_RightCurlyBracketKeyword_5_p__q;
	protected AbstractElementAlias match_Vertrag_RightCurlyBracketKeyword_5_a;
	protected AbstractElementAlias match_Vertrag_RightCurlyBracketKeyword_5_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (VertragGrammarAccess) access;
		match_Handy_RightCurlyBracketKeyword_3_a = new TokenAlias(true, true, grammarAccess.getHandyAccess().getRightCurlyBracketKeyword_3());
		match_Handy_RightCurlyBracketKeyword_3_p = new TokenAlias(true, false, grammarAccess.getHandyAccess().getRightCurlyBracketKeyword_3());
		match_Handy_Vertrag___RightCurlyBracketKeyword_3_p_or_RightCurlyBracketKeyword_5_p__q = new AlternativeAlias(false, true, new TokenAlias(true, false, grammarAccess.getHandyAccess().getRightCurlyBracketKeyword_3()), new TokenAlias(true, false, grammarAccess.getVertragAccess().getRightCurlyBracketKeyword_5()));
		match_Vertrag_RightCurlyBracketKeyword_5_a = new TokenAlias(true, true, grammarAccess.getVertragAccess().getRightCurlyBracketKeyword_5());
		match_Vertrag_RightCurlyBracketKeyword_5_p = new TokenAlias(true, false, grammarAccess.getVertragAccess().getRightCurlyBracketKeyword_5());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Handy_RightCurlyBracketKeyword_3_a.equals(syntax))
				emit_Handy_RightCurlyBracketKeyword_3_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Handy_RightCurlyBracketKeyword_3_p.equals(syntax))
				emit_Handy_RightCurlyBracketKeyword_3_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Handy_Vertrag___RightCurlyBracketKeyword_3_p_or_RightCurlyBracketKeyword_5_p__q.equals(syntax))
				emit_Handy_Vertrag___RightCurlyBracketKeyword_3_p_or_RightCurlyBracketKeyword_5_p__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Vertrag_RightCurlyBracketKeyword_5_a.equals(syntax))
				emit_Vertrag_RightCurlyBracketKeyword_5_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Vertrag_RightCurlyBracketKeyword_5_p.equals(syntax))
				emit_Vertrag_RightCurlyBracketKeyword_5_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '}'*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'handy' name=ID
	 *     (rule start) (ambiguity) 'marke' marke=ID
	 *     (rule start) (ambiguity) 'speicher' speicher=INT
	 *     (rule start) (ambiguity) (rule start)
	 *     marke=ID (ambiguity) 'handy' name=ID
	 *     marke=ID (ambiguity) 'marke' marke=ID
	 *     marke=ID (ambiguity) 'speicher' speicher=INT
	 *     marke=ID (ambiguity) (rule end)
	 *     name=ID '{' (ambiguity) 'handy' name=ID
	 *     name=ID '{' (ambiguity) 'marke' marke=ID
	 *     name=ID '{' (ambiguity) 'speicher' speicher=INT
	 *     name=ID '{' (ambiguity) (rule end)
	 *     speicher=INT (ambiguity) 'handy' name=ID
	 *     speicher=INT (ambiguity) 'marke' marke=ID
	 *     speicher=INT (ambiguity) 'speicher' speicher=INT
	 *     speicher=INT (ambiguity) (rule end)
	 *     system=ID (ambiguity) 'handy' name=ID
	 *     system=ID (ambiguity) 'marke' marke=ID
	 *     system=ID (ambiguity) 'speicher' speicher=INT
	 *     system=ID (ambiguity) (rule end)
	 */
	protected void emit_Handy_RightCurlyBracketKeyword_3_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '}'+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_Handy_RightCurlyBracketKeyword_3_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('}'+ | '}'+)?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_Handy_Vertrag___RightCurlyBracketKeyword_3_p_or_RightCurlyBracketKeyword_5_p__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '}'*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'Vertrag' name=ID
	 *     (rule start) (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     (rule start) (ambiguity) 'internetseite' internetseite=ID
	 *     (rule start) (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     (rule start) (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     (rule start) (ambiguity) (rule start)
	 *     datenvolumen=INT (ambiguity) 'Vertrag' name=ID
	 *     datenvolumen=INT (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     datenvolumen=INT (ambiguity) 'internetseite' internetseite=ID
	 *     datenvolumen=INT (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     datenvolumen=INT (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     datenvolumen=INT (ambiguity) (rule end)
	 *     internetseite=ID (ambiguity) 'Vertrag' name=ID
	 *     internetseite=ID (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     internetseite=ID (ambiguity) 'internetseite' internetseite=ID
	 *     internetseite=ID (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     internetseite=ID (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     internetseite=ID (ambiguity) (rule end)
	 *     mindestvertragslaufzeit=INT (ambiguity) 'Vertrag' name=ID
	 *     mindestvertragslaufzeit=INT (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     mindestvertragslaufzeit=INT (ambiguity) 'internetseite' internetseite=ID
	 *     mindestvertragslaufzeit=INT (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     mindestvertragslaufzeit=INT (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     mindestvertragslaufzeit=INT (ambiguity) (rule end)
	 *     monatl_kosten=FLOAT (ambiguity) 'Vertrag' name=ID
	 *     monatl_kosten=FLOAT (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     monatl_kosten=FLOAT (ambiguity) 'internetseite' internetseite=ID
	 *     monatl_kosten=FLOAT (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     monatl_kosten=FLOAT (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     monatl_kosten=FLOAT (ambiguity) (rule end)
	 *     name=ID '{' (ambiguity) 'Vertrag' name=ID
	 *     name=ID '{' (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     name=ID '{' (ambiguity) 'internetseite' internetseite=ID
	 *     name=ID '{' (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     name=ID '{' (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     name=ID '{' (ambiguity) (rule end)
	 *     netzanbieter=ID (ambiguity) 'Vertrag' name=ID
	 *     netzanbieter=ID (ambiguity) 'datenvolumen' datenvolumen=INT
	 *     netzanbieter=ID (ambiguity) 'internetseite' internetseite=ID
	 *     netzanbieter=ID (ambiguity) 'monatl_kosten' monatl_kosten=FLOAT
	 *     netzanbieter=ID (ambiguity) 'netzanbieter' netzanbieter=ID
	 *     netzanbieter=ID (ambiguity) (rule end)
	 */
	protected void emit_Vertrag_RightCurlyBracketKeyword_5_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '}'+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_Vertrag_RightCurlyBracketKeyword_5_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
