/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.services.VertragGrammarAccess;
import org.xtext.example.mydsl.vertrag.Handy;
import org.xtext.example.mydsl.vertrag.Model;
import org.xtext.example.mydsl.vertrag.Vertrag;
import org.xtext.example.mydsl.vertrag.VertragPackage;

@SuppressWarnings("all")
public class VertragSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private VertragGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == VertragPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case VertragPackage.HANDY:
				sequence_Handy(context, (Handy) semanticObject); 
				return; 
			case VertragPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case VertragPackage.VERTRAG:
				sequence_Vertrag(context, (Vertrag) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Element returns Handy
	 *     Handy returns Handy
	 *
	 * Constraint:
	 *     (name=ID system?=ID marke?=ID speicher?=ID)
	 */
	protected void sequence_Handy(ISerializationContext context, Handy semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, VertragPackage.Literals.ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VertragPackage.Literals.ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, VertragPackage.Literals.HANDY__SYSTEM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VertragPackage.Literals.HANDY__SYSTEM));
			if (transientValues.isValueTransient(semanticObject, VertragPackage.Literals.HANDY__MARKE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VertragPackage.Literals.HANDY__MARKE));
			if (transientValues.isValueTransient(semanticObject, VertragPackage.Literals.HANDY__SPEICHER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VertragPackage.Literals.HANDY__SPEICHER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getHandyAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getHandyAccess().getSystemIDTerminalRuleCall_3_0(), semanticObject.isSystem());
		feeder.accept(grammarAccess.getHandyAccess().getMarkeIDTerminalRuleCall_4_0(), semanticObject.isMarke());
		feeder.accept(grammarAccess.getHandyAccess().getSpeicherIDTerminalRuleCall_5_0(), semanticObject.isSpeicher());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     elements+=Element+
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Element returns Vertrag
	 *     Vertrag returns Vertrag
	 *
	 * Constraint:
	 *     (
	 *         (mindestvertragslaufzeit=ZEICHENFOLGE | monatl_kosten=ZEICHENFOLGE | netzanbieter=ZEICHENFOLGE)? 
	 *         (name=ZEICHENFOLGE datenvolumen=ZEICHENFOLGE*)?
	 *     )+
	 */
	protected void sequence_Vertrag(ISerializationContext context, Vertrag semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
