/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.xtext.example.mydsl.services.VertragGrammarAccess;
import org.xtext.example.mydsl.vertrag.Handy;
import org.xtext.example.mydsl.vertrag.Model;
import org.xtext.example.mydsl.vertrag.Vertrag;
import org.xtext.example.mydsl.vertrag.VertragPackage;

@SuppressWarnings("all")
public class VertragSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private VertragGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == VertragPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case VertragPackage.HANDY:
				sequence_Handy(context, (Handy) semanticObject); 
				return; 
			case VertragPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case VertragPackage.VERTRAG:
				sequence_Vertrag(context, (Vertrag) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Element returns Handy
	 *     Handy returns Handy
	 *
	 * Constraint:
	 *     ((marke=ID | speicher=INT)? (name=ID system=ID?)?)+
	 */
	protected void sequence_Handy(ISerializationContext context, Handy semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     elements+=Element+
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Element returns Vertrag
	 *     Vertrag returns Vertrag
	 *
	 * Constraint:
	 *     ((datenvolumen=INT | monatl_kosten=FLOAT | netzanbieter=ID | internetseite=ID)? (name=ID mindestvertragslaufzeit=INT*)?)+
	 */
	protected void sequence_Vertrag(ISerializationContext context, Vertrag semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
