/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.VertragStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class VertragStandaloneSetup extends VertragStandaloneSetupGenerated {
  public static void doSetup() {
    new VertragStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
