/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.example.mydsl.validation.AbstractVertragValidator;
import org.xtext.example.mydsl.vertrag.Vertrag;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class VertragValidator extends AbstractVertragValidator {
  @Check
  public Object checkVertrag(final Vertrag ver) {
    return null;
  }
}
