/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.vertrag;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Handy</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.vertrag.Handy#getSystem <em>System</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.vertrag.Handy#getMarke <em>Marke</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.vertrag.Handy#getSpeicher <em>Speicher</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.vertrag.VertragPackage#getHandy()
 * @model
 * @generated
 */
public interface Handy extends Element
{
  /**
   * Returns the value of the '<em><b>System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>System</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>System</em>' attribute.
   * @see #setSystem(String)
   * @see org.xtext.example.mydsl.vertrag.VertragPackage#getHandy_System()
   * @model
   * @generated
   */
  String getSystem();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.vertrag.Handy#getSystem <em>System</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>System</em>' attribute.
   * @see #getSystem()
   * @generated
   */
  void setSystem(String value);

  /**
   * Returns the value of the '<em><b>Marke</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Marke</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Marke</em>' attribute.
   * @see #setMarke(String)
   * @see org.xtext.example.mydsl.vertrag.VertragPackage#getHandy_Marke()
   * @model
   * @generated
   */
  String getMarke();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.vertrag.Handy#getMarke <em>Marke</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Marke</em>' attribute.
   * @see #getMarke()
   * @generated
   */
  void setMarke(String value);

  /**
   * Returns the value of the '<em><b>Speicher</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Speicher</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speicher</em>' attribute.
   * @see #setSpeicher(int)
   * @see org.xtext.example.mydsl.vertrag.VertragPackage#getHandy_Speicher()
   * @model
   * @generated
   */
  int getSpeicher();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.vertrag.Handy#getSpeicher <em>Speicher</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Speicher</em>' attribute.
   * @see #getSpeicher()
   * @generated
   */
  void setSpeicher(int value);

} // Handy
