/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.vertrag;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Netzanbieter</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.vertrag.VertragPackage#getNetzanbieter()
 * @model
 * @generated
 */
public enum Netzanbieter implements Enumerator
{
  /**
   * The '<em><b>O2</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #O2_VALUE
   * @generated
   * @ordered
   */
  O2(0, "O2", "O2"),

  /**
   * The '<em><b>TELEKOM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TELEKOM_VALUE
   * @generated
   * @ordered
   */
  TELEKOM(1, "TELEKOM", "TELEKOM"),

  /**
   * The '<em><b>VODAFON</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #VODAFON_VALUE
   * @generated
   * @ordered
   */
  VODAFON(2, "VODAFON", "VODAFON");

  /**
   * The '<em><b>O2</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>O2</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #O2
   * @model
   * @generated
   * @ordered
   */
  public static final int O2_VALUE = 0;

  /**
   * The '<em><b>TELEKOM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TELEKOM</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TELEKOM
   * @model
   * @generated
   * @ordered
   */
  public static final int TELEKOM_VALUE = 1;

  /**
   * The '<em><b>VODAFON</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>VODAFON</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #VODAFON
   * @model
   * @generated
   * @ordered
   */
  public static final int VODAFON_VALUE = 2;

  /**
   * An array of all the '<em><b>Netzanbieter</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Netzanbieter[] VALUES_ARRAY =
    new Netzanbieter[]
    {
      O2,
      TELEKOM,
      VODAFON,
    };

  /**
   * A public read-only list of all the '<em><b>Netzanbieter</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Netzanbieter> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Netzanbieter</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Netzanbieter get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Netzanbieter result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Netzanbieter</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Netzanbieter getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Netzanbieter result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Netzanbieter</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Netzanbieter get(int value)
  {
    switch (value)
    {
      case O2_VALUE: return O2;
      case TELEKOM_VALUE: return TELEKOM;
      case VODAFON_VALUE: return VODAFON;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Netzanbieter(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Netzanbieter
