/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.vertrag;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.vertrag.VertragFactory
 * @model kind="package"
 * @generated
 */
public interface VertragPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "vertrag";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Vertrag";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "vertrag";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VertragPackage eINSTANCE = org.xtext.example.mydsl.vertrag.impl.VertragPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.vertrag.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.vertrag.impl.ModelImpl
   * @see org.xtext.example.mydsl.vertrag.impl.VertragPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.vertrag.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.vertrag.impl.ElementImpl
   * @see org.xtext.example.mydsl.vertrag.impl.VertragPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.vertrag.impl.VertragImpl <em>Vertrag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.vertrag.impl.VertragImpl
   * @see org.xtext.example.mydsl.vertrag.impl.VertragPackageImpl#getVertrag()
   * @generated
   */
  int VERTRAG = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Mindestvertragslaufzeit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG__MINDESTVERTRAGSLAUFZEIT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Datenvolumen</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG__DATENVOLUMEN = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Monatl kosten</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG__MONATL_KOSTEN = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Netzanbieter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG__NETZANBIETER = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Internetseite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG__INTERNETSEITE = ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Vertrag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTRAG_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.vertrag.impl.HandyImpl <em>Handy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.vertrag.impl.HandyImpl
   * @see org.xtext.example.mydsl.vertrag.impl.VertragPackageImpl#getHandy()
   * @generated
   */
  int HANDY = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HANDY__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HANDY__SYSTEM = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Marke</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HANDY__MARKE = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Speicher</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HANDY__SPEICHER = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Handy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HANDY_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.vertrag.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.vertrag.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.vertrag.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.mydsl.vertrag.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.vertrag.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.example.mydsl.vertrag.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.vertrag.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.vertrag.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.vertrag.Vertrag <em>Vertrag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertrag</em>'.
   * @see org.xtext.example.mydsl.vertrag.Vertrag
   * @generated
   */
  EClass getVertrag();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.vertrag.Vertrag#getMindestvertragslaufzeit <em>Mindestvertragslaufzeit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mindestvertragslaufzeit</em>'.
   * @see org.xtext.example.mydsl.vertrag.Vertrag#getMindestvertragslaufzeit()
   * @see #getVertrag()
   * @generated
   */
  EAttribute getVertrag_Mindestvertragslaufzeit();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.vertrag.Vertrag#getDatenvolumen <em>Datenvolumen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Datenvolumen</em>'.
   * @see org.xtext.example.mydsl.vertrag.Vertrag#getDatenvolumen()
   * @see #getVertrag()
   * @generated
   */
  EAttribute getVertrag_Datenvolumen();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.vertrag.Vertrag#getMonatl_kosten <em>Monatl kosten</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Monatl kosten</em>'.
   * @see org.xtext.example.mydsl.vertrag.Vertrag#getMonatl_kosten()
   * @see #getVertrag()
   * @generated
   */
  EAttribute getVertrag_Monatl_kosten();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.vertrag.Vertrag#getNetzanbieter <em>Netzanbieter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Netzanbieter</em>'.
   * @see org.xtext.example.mydsl.vertrag.Vertrag#getNetzanbieter()
   * @see #getVertrag()
   * @generated
   */
  EAttribute getVertrag_Netzanbieter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.vertrag.Vertrag#getInternetseite <em>Internetseite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Internetseite</em>'.
   * @see org.xtext.example.mydsl.vertrag.Vertrag#getInternetseite()
   * @see #getVertrag()
   * @generated
   */
  EAttribute getVertrag_Internetseite();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.vertrag.Handy <em>Handy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Handy</em>'.
   * @see org.xtext.example.mydsl.vertrag.Handy
   * @generated
   */
  EClass getHandy();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.vertrag.Handy#getSystem <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>System</em>'.
   * @see org.xtext.example.mydsl.vertrag.Handy#getSystem()
   * @see #getHandy()
   * @generated
   */
  EAttribute getHandy_System();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.vertrag.Handy#getMarke <em>Marke</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Marke</em>'.
   * @see org.xtext.example.mydsl.vertrag.Handy#getMarke()
   * @see #getHandy()
   * @generated
   */
  EAttribute getHandy_Marke();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.vertrag.Handy#getSpeicher <em>Speicher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speicher</em>'.
   * @see org.xtext.example.mydsl.vertrag.Handy#getSpeicher()
   * @see #getHandy()
   * @generated
   */
  EAttribute getHandy_Speicher();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VertragFactory getVertragFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.vertrag.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.vertrag.impl.ModelImpl
     * @see org.xtext.example.mydsl.vertrag.impl.VertragPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.vertrag.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.vertrag.impl.ElementImpl
     * @see org.xtext.example.mydsl.vertrag.impl.VertragPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.vertrag.impl.VertragImpl <em>Vertrag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.vertrag.impl.VertragImpl
     * @see org.xtext.example.mydsl.vertrag.impl.VertragPackageImpl#getVertrag()
     * @generated
     */
    EClass VERTRAG = eINSTANCE.getVertrag();

    /**
     * The meta object literal for the '<em><b>Mindestvertragslaufzeit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTRAG__MINDESTVERTRAGSLAUFZEIT = eINSTANCE.getVertrag_Mindestvertragslaufzeit();

    /**
     * The meta object literal for the '<em><b>Datenvolumen</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTRAG__DATENVOLUMEN = eINSTANCE.getVertrag_Datenvolumen();

    /**
     * The meta object literal for the '<em><b>Monatl kosten</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTRAG__MONATL_KOSTEN = eINSTANCE.getVertrag_Monatl_kosten();

    /**
     * The meta object literal for the '<em><b>Netzanbieter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTRAG__NETZANBIETER = eINSTANCE.getVertrag_Netzanbieter();

    /**
     * The meta object literal for the '<em><b>Internetseite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTRAG__INTERNETSEITE = eINSTANCE.getVertrag_Internetseite();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.vertrag.impl.HandyImpl <em>Handy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.vertrag.impl.HandyImpl
     * @see org.xtext.example.mydsl.vertrag.impl.VertragPackageImpl#getHandy()
     * @generated
     */
    EClass HANDY = eINSTANCE.getHandy();

    /**
     * The meta object literal for the '<em><b>System</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HANDY__SYSTEM = eINSTANCE.getHandy_System();

    /**
     * The meta object literal for the '<em><b>Marke</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HANDY__MARKE = eINSTANCE.getHandy_Marke();

    /**
     * The meta object literal for the '<em><b>Speicher</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HANDY__SPEICHER = eINSTANCE.getHandy_Speicher();

  }

} //VertragPackage
